/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interf;

import Codes.DBconnect;
import Codes.Validation;
import Codes.exam;
import Codes.grades;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author Dinuksha
 */
public class AddExamdetails extends javax.swing.JInternalFrame {
    Connection con = null;
    PreparedStatement pst = null;
    exam exam1;
    /**
     * Creates new form AddExamdetails
     */
    public AddExamdetails() {
        initComponents();
        con = DBconnect.connect();
        exam1  = new exam(pst,con);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1500, 600));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel1.setText("Exam:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(710, 80, 60, 20);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(950, 80, 300, 30);

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setText("Description");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(710, 160, 90, 23);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(950, 150, 300, 30);

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel3.setText("Academic Year");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(710, 230, 110, 23);

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel4.setText("Semester");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(710, 300, 100, 23);

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel5.setText("Exam Date (yyyy/mm/dd)");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(710, 370, 210, 23);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(950, 360, 300, 30);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1110, 450, 100, 45);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/study.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(100, 40, 460, 410);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "1", "2", "3", "4" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(950, 230, 300, 30);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "1", "2", "3", "4", "5", "6", "7", "8" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(950, 290, 300, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Light-Blue-blur-background1.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(-30, 0, 1430, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if(jTextField1.getText()==""||jTextField2.getText()==""||jComboBox1.getSelectedItem().toString()=="Select"||jComboBox2.getSelectedItem().toString()=="Select"||jTextField5.getText()=="")
        {
            JOptionPane.showMessageDialog(null, "Please fill all the fields!");  
        }
        else if(!Validation.isValidDate(jTextField5.getText()))
            {
                JOptionPane.showMessageDialog(null, "Please Enter a Valid Date!");
            }
        else if(Validation.validateSemester(Integer.parseInt(jComboBox1.getSelectedItem().toString()),Integer.parseInt(jComboBox2.getSelectedItem().toString())))
            {
                String exam_name = jTextField1.getText();
                String description = jTextField2.getText();
                int year = Integer.parseInt(jComboBox1.getSelectedItem().toString());
                int semester = Integer.parseInt(jComboBox2.getSelectedItem().toString());
                String date = jTextField5.getText();
                exam1.addNewExam(exam_name, description, year, semester, date);
            }
            else{
                JOptionPane.showMessageDialog(null, "Please Select a Valid Semester");
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        int acYear = Integer.parseInt(jComboBox1.getSelectedItem().toString());
        int sem = Integer.parseInt(jComboBox2.getSelectedItem().toString());
        
        if(!Validation.validateSemester(acYear, sem)){
            JOptionPane.showMessageDialog(null,"Invalid choice");
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
