/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interf;
import Codes.DBconnect;
import Codes.addlecturer;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;


import Codes.addlecturer;

/**
 *
 * @author Joel
 */
public class addLect extends javax.swing.JInternalFrame {
    Connection con=null; 
    PreparedStatement pst=null;
    /**
     * Creates new form addLect
     */
    public addLect() {
        initComponents();
        con=DBconnect.connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lposition = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        laddress = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lemail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        lphone = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lpass = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setResizable(true);
        setTitle("Add a new lecturer");
        setPreferredSize(new java.awt.Dimension(890, 550));
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        jLabel3.setText("Add New Lecturer");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 50, 141, 25);

        jLabel4.setText("Name:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(140, 110, 70, 50);
        getContentPane().add(lname);
        lname.setBounds(220, 120, 220, 30);

        jLabel5.setText("Position:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(140, 160, 80, 50);

        lposition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lpositionActionPerformed(evt);
            }
        });
        getContentPane().add(lposition);
        lposition.setBounds(220, 170, 220, 30);

        jLabel1.setText("Address:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 220, 70, 50);

        laddress.setToolTipText("");
        laddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laddressActionPerformed(evt);
            }
        });
        getContentPane().add(laddress);
        laddress.setBounds(220, 230, 220, 30);

        jLabel6.setText("E-mail:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(140, 280, 70, 50);
        getContentPane().add(lemail);
        lemail.setBounds(220, 290, 220, 30);

        jLabel7.setText("Phone:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(140, 340, 80, 50);
        getContentPane().add(lphone);
        lphone.setBounds(220, 350, 220, 30);

        jLabel2.setText("Password:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(140, 390, 80, 70);
        getContentPane().add(lpass);
        lpass.setBounds(220, 410, 220, 30);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button(9).png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addpressed.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(540, 460, 100, 40);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button(10).png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancelpressed.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(670, 460, 100, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lpositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lpositionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lpositionActionPerformed

    private void laddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_laddressActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String name=lname.getText();
        String position=lposition.getText();
        String address=laddress.getText();
        String email=lemail.getText();
        String phone=lphone.getText();
        String pass=lpass.getText();
        
       if(!name.equals("") & !position.equals("") & !address.equals("") & !email.equals("") & !phone.equals("") & !pass.equals(""))
       {
        addlecturer a = new addlecturer();
        
        if(a.addNewLecturer(pst, con, name, position, email, phone, address, pass))
        {
           lname.setText(null);
           lposition.setText(null);
           laddress.setText(null);
           lemail.setText(null);
           lphone.setText(null);
           lpass.setText(null);
        }
       }
       else
       {
           JOptionPane.showMessageDialog(null,"Please fill in all required information!");
       }    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField laddress;
    private javax.swing.JTextField lemail;
    private javax.swing.JTextField lname;
    private javax.swing.JTextField lpass;
    private javax.swing.JTextField lphone;
    private javax.swing.JTextField lposition;
    // End of variables declaration//GEN-END:variables
}
