/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interf;

import Codes.DBconnect;
import Codes.ProfilePicture;
import Codes.Validation;
import Codes.student;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Dinuksha
 */
public class AddStudent extends javax.swing.JInternalFrame {
    Connection con = null;
    PreparedStatement pst = null;
    String sid;
    Validation validate;
    /**
     * Creates new form AddStudent
     */
    public AddStudent() {
        initComponents();
        con = DBconnect.connect();
        fillCombo();
        validate = new Validation(con,pst);
    }
    
    //method to fill the combo box
    private void fillCombo(){
        try{
            String sql = "Select * from program";
            pst= con.prepareStatement(sql);
            ResultSet r1 = pst.executeQuery();
            String name;
            while(r1.next()){
                if(r1.getString("specialization")==null){
                    name = r1.getString("name");
                }
                else{
                    name = r1.getString("name")+" "+r1.getString("specialization");
                }
                degree.addItem(name);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        mname = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        ad = new javax.swing.JTextField();
        tpnum = new javax.swing.JTextField();
        dob = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        degree = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1600, 700));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("First Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(400, 120, 90, 23);

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Last Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(400, 220, 100, 23);

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Middle Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(400, 170, 120, 23);

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Address");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(400, 270, 70, 23);

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Telephone No.");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(400, 320, 110, 23);

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Date Of Birth (yyyy/mm/dd)");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(400, 370, 210, 23);

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("E-mail");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(400, 410, 60, 23);

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Degree Program");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(400, 460, 120, 23);

        fname.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameActionPerformed(evt);
            }
        });
        getContentPane().add(fname);
        fname.setBounds(630, 110, 290, 30);

        mname.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        getContentPane().add(mname);
        mname.setBounds(630, 160, 290, 30);

        lname.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        getContentPane().add(lname);
        lname.setBounds(630, 210, 290, 30);

        ad.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        ad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adActionPerformed(evt);
            }
        });
        getContentPane().add(ad);
        ad.setBounds(630, 260, 290, 30);

        tpnum.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        getContentPane().add(tpnum);
        tpnum.setBounds(630, 310, 290, 30);

        dob.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        dob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobActionPerformed(evt);
            }
        });
        getContentPane().add(dob);
        dob.setBounds(630, 360, 290, 30);

        email.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        getContentPane().add(email);
        email.setBounds(630, 410, 290, 30);

        degree.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        degree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                degreeActionPerformed(evt);
            }
        });
        getContentPane().add(degree);
        degree.setBounds(630, 460, 420, 30);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/register.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1110, 460, 110, 40);

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Student Registration");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(650, 40, 240, 60);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/grad.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(90, 180, 320, 480);
        getContentPane().add(jLabel12);
        jLabel12.setBounds(1130, 110, 140, 170);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BrowseImg.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BrowseImgPressed.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(1010, 330, 160, 40);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/setImg.png"))); // NOI18N
        jButton3.setContentAreaFilled(false);
        jButton3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/setImgPressed.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(1190, 330, 130, 40);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(1020, 290, 290, 20);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background_2.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 1560, 740);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameActionPerformed

    private void adActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adActionPerformed

    private void dobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dobActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     
        String first_name = fname.getText();
        String middle_name = mname.getText();
        String last_name = lname.getText();
        String address = ad.getText();
        String phone = tpnum.getText();
        String date_of_birth = dob.getText();
        String mail = email.getText();
        String p = degree.getSelectedItem().toString();
        
        if(first_name.equals("") || middle_name.equals("") || last_name.equals("") || address.equals("") || phone.equals("") || date_of_birth.equals("") || mail.equals("") || p.equals(""))
        {
            JOptionPane.showMessageDialog(null, "All Fields Must Be Filled!");
        }
        else if (!Validation.isValidBirthDate(date_of_birth))
            {
                JOptionPane.showMessageDialog(null, "Please enter a Valid Date!");
            }
            else if(!Validation.validateNumber(phone)||phone.length()!=10){
                    JOptionPane.showMessageDialog(null, "Please enter a Valid Telephone Number!");
                }
                else
                {
                    student s = new student(con,pst);
                    sid = s.generateIdNumber(con, pst, p);
                    s.addNewStudent(sid, first_name, middle_name, last_name, address, phone, date_of_birth, mail, p,1);
                }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void degreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_degreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_degreeActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ProfilePicture.setImage(jTextField1, pst, con, sid);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        ProfilePicture.browseImage(jTextField1, jLabel12);
    }//GEN-LAST:event_jButton2ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ad;
    private javax.swing.JComboBox degree;
    private javax.swing.JTextField dob;
    private javax.swing.JTextField email;
    private javax.swing.JTextField fname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField lname;
    private javax.swing.JTextField mname;
    private javax.swing.JTextField tpnum;
    // End of variables declaration//GEN-END:variables
}
