/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interf;

import Codes.DBconnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Himasha Harinda
 */
public class assignLecturerCourse extends javax.swing.JFrame {

    Connection con = null;
    Connection con1 = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    ResultSet rs1 = null;
    ResultSet rs2 = null;
    
    
    
    
    
    /**
     * Creates new form assignLecturerCourse
     */
    public assignLecturerCourse() {
        initComponents();
        con = DBconnect.connect();
        con1 = DBconnect.connect();
        fillcombo1();
        fillcombo2();
        tableload();
    }
    
    public void tableload()
    {
        
        
        try {
            
            
            
            String sql = "SELECT l.name AS Lecturer, c.name AS Course FROM lecturer l,course c, lecturer_courses lc WHERE lc.lecturer = l.lec_id and lc.course = c.Course_id";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            
            lctable.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch (Exception e) {
        }
        
    }
    
   
    
    
    private void fillcombo1()
    {
        try {
            String sql = "SELECT * FROM lecturer";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            
            while(rs.next())
            {
                String name = rs.getString("name");
                lecid.addItem(name);
            }
            
            
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    
    private void fillcombo2()
    {
        try {
            String sql = "SELECT * FROM course";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            
            while(rs.next())
            {
                String name = rs.getString("name");
                coid.addItem(name);
            }
            
            
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lecid = new javax.swing.JComboBox();
        coid = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        lctable = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Merideth-blog-post11.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(300, 70));
        setPreferredSize(new java.awt.Dimension(770, 525));
        setResizable(false);
        setSize(new java.awt.Dimension(770, 525));
        getContentPane().setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/assign.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/assign_clicked.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(140, 390, 120, 34);

        jLabel1.setText("Lecturer ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(210, 230, 90, 30);

        jLabel2.setText("Course ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(210, 260, 90, 30);

        lecid.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Lecturer" }));
        getContentPane().add(lecid);
        lecid.setBounds(330, 230, 211, 30);

        coid.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Course" }));
        getContentPane().add(coid);
        coid.setBounds(330, 260, 211, 30);

        lctable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        lctable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lctableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lctable);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(136, 34, 452, 129);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button(13).png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pressedupdate.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(300, 390, 120, 34);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button(17).png"))); // NOI18N
        jButton3.setContentAreaFilled(false);
        jButton3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/presseddelete.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(470, 390, 120, 34);

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rsz_arrow-back-icon.png"))); // NOI18N
        jButton4.setText("Back");
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(630, 0, 140, 50);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Light-Blue-blur-background1.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(-10, -90, 920, 630);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        int x = JOptionPane.showConfirmDialog(null,"Are yoou sure you want to assign?");
        
        if(x==0)
        {
            String lecname = lecid.getSelectedItem().toString();
            String courseName = coid.getSelectedItem().toString();
        
            String r1 = "SELECT * FROM lecturer WHERE name = '"+ lecname +"'";
            String r2 = "SELECT * FROM course WHERE name = '"+ courseName +"'";
            
            try {
                pst = con.prepareStatement(r1);
                rs = pst.executeQuery();
            
                pst = con.prepareStatement(r2);
                rs1 = pst.executeQuery();
                
                boolean exist = false;
                
                while(rs.next() && rs1.next())
                {
                    int lecid1 = rs.getInt("lec_id");
                    int coid1 = rs1.getInt("Course_id");
                    
                    String q = "SELECT * FROM lecturer_courses WHERE lecturer = '"+ lecid1 +"' AND course = '"+ coid1 +"'";
                    String query = "INSERT INTO lecturer_courses (lecturer,course) VALUES ('"+ lecid1 +"','"+ coid1 +"')";
                    
                    pst = con.prepareStatement(q);
                    rs = pst.executeQuery();
                    
                    
                    while(rs.next())
                    {
                        int n = rs.getInt("lecturer");
                        int p = rs.getInt("course");
                    
                        if(n == lecid1 && p == coid1)
                        {
                            JOptionPane.showMessageDialog(null,"Data already exists !");
                            exist = true;
                        }
                    }
                    
                    
                    if(exist == false)
                    {
                        pst = con1.prepareStatement(query);
                        pst.execute();
                        
                        JOptionPane.showMessageDialog(null," Data added successfully ! ");
                    }
                
                    tableload();
                }
        
        } catch (Exception e){
        }
         
        }
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lctableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lctableMouseClicked
        
        int r = lctable.getSelectedRow();
        String lec = lctable.getValueAt(r, 0).toString();
        String co = lctable.getValueAt(r, 1).toString();
        
        lecid.setSelectedItem(lec);
        coid.setSelectedItem(co);
        
        
        
        
    }//GEN-LAST:event_lctableMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        int x = JOptionPane.showConfirmDialog(null, "Are you sure you want to update?");
        if(x ==0)
        {
            String lecname = lecid.getSelectedItem().toString();
            String coname = coid.getSelectedItem().toString();
            
            String r3 = "SELECT * FROM lecturer WHERE name = '"+ lecname +"'";
            String r4 = "SELECT * FROM course WHERE name = '"+ coname +"'";
            
            try {
                
                pst = con.prepareStatement(r3);
                rs = pst.executeQuery();
                
                pst = con.prepareStatement(r4);
                rs1 = pst.executeQuery();
                
                while(rs.next() && rs1.next())
                {
                    int lecid1 = rs.getInt("lec_id");
                    int coid1 = rs1.getInt("Course_id");
                    
                    String query = "UPDATE lecturer_courses SET lecturer = '"+ lecid1 +"' , course = '"+ coid1 +"'";
            
                    pst = con1.prepareStatement(query);
                    pst.execute();
                    
                    JOptionPane.showMessageDialog(null, "Data updated successfully !");
                
                    tableload();
                    
                    
                }
                
            } catch (Exception e) {
            }
            
        }
        
        
                
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        int x = JOptionPane.showConfirmDialog(null,"Are you sure you want to delete?");
            if(x == 0)
            {
                String lecname = lecid.getSelectedItem().toString();
                String coname = coid.getSelectedItem().toString();
                
                String r1 = "SELECT * FROM lecturer WHERE name = '"+ lecname +"'";
                String r2 = "SELECT * FROM course WHERE name = '"+ coname +"'";
                
                try {
                    
                    pst = con.prepareStatement(r1);
                    rs = pst.executeQuery();
                    
                    pst = con.prepareStatement(r2);
                    rs1 = pst.executeQuery();
                    
                    while(rs.next() && rs1.next())
                    {
                        int lecid1 = rs.getInt("lec_id");
                        int coid1 = rs1.getInt("Course_id");
                    
                        String qy = "DELETE FROM lecturer_courses WHERE lecturer = '"+ lecid1 +"' AND course = '"+ coid1 +"'";
            
                        pst = con1.prepareStatement(qy);
                        pst.execute();
                        
                        JOptionPane.showMessageDialog(null, " Data deleted sucessfully ! ");
                
                        tableload();
                    }
                    
                } catch (Exception e) {
                }
            }
            
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(assignLecturerCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(assignLecturerCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(assignLecturerCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(assignLecturerCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new assignLecturerCourse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox coid;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable lctable;
    private javax.swing.JComboBox lecid;
    // End of variables declaration//GEN-END:variables
}
