/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interf;

import Codes.DBconnect;
import Codes.ProfilePicture;
import Codes.Validation;
import Codes.student;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Dinuksha
 */
public class UpdateStudent extends javax.swing.JInternalFrame {
    Connection con2 = null;
    PreparedStatement pst2 = null;
    student s;
    Validation validate;
    /**
     * Creates new form UpdateStudent
     */
    public UpdateStudent() {
        initComponents();
        con2 = DBconnect.connect();
        s = new student(con2,pst2);
        s.viewStudent(jTable1);
        validate = new Validation(con2,pst2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        dob2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        email2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        fname2 = new javax.swing.JTextField();
        mname2 = new javax.swing.JTextField();
        lname2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        ad2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tpnum2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        semester = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1600, 700));
        getContentPane().setLayout(null);

        jTable1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(240, 240, 240));
        jTable1.setIntercellSpacing(new java.awt.Dimension(2, 2));
        jTable1.setShowHorizontalLines(false);
        jTable1.setShowVerticalLines(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(840, 50, 500, 350);

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Middle Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(370, 250, 98, 23);

        dob2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        dob2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dob2ActionPerformed(evt);
            }
        });
        getContentPane().add(dob2);
        dob2.setBounds(560, 410, 247, 29);

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Address");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(370, 330, 57, 23);

        email2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        getContentPane().add(email2);
        email2.setBounds(560, 450, 247, 28);

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Telephone No.");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(370, 370, 108, 23);

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Date Of Birth");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(370, 410, 96, 23);

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Semester");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(370, 490, 90, 23);

        fname2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        fname2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fname2ActionPerformed(evt);
            }
        });
        getContentPane().add(fname2);
        fname2.setBounds(560, 210, 247, 29);

        mname2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        getContentPane().add(mname2);
        mname2.setBounds(560, 250, 247, 29);

        lname2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        getContentPane().add(lname2);
        lname2.setBounds(560, 290, 247, 30);

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("First Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(370, 210, 79, 23);

        ad2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        ad2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ad2ActionPerformed(evt);
            }
        });
        getContentPane().add(ad2);
        ad2.setBounds(560, 330, 247, 30);

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Last Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(370, 290, 78, 23);

        tpnum2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        getContentPane().add(tpnum2);
        tpnum2.setBounds(560, 370, 247, 29);

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Student ID");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(370, 170, 76, 23);

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel9);
        jLabel9.setBounds(560, 170, 240, 22);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update2.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(860, 430, 99, 32);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(860, 480, 100, 32);

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Update Student Record");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(560, 50, 240, 30);

        jLabel12.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("* Select the record from the table on the right which should be updated");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(280, 110, 580, 30);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background_img.png"))); // NOI18N
        getContentPane().add(jLabel20);
        jLabel20.setBounds(-30, 150, 490, 410);
        getContentPane().add(jLabel13);
        jLabel13.setBounds(90, 120, 130, 170);

        jLabel14.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("E-mail");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(370, 450, 46, 23);

        semester.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        semester.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", " " }));
        getContentPane().add(semester);
        semester.setBounds(560, 490, 70, 30);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background_2.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(-10, -30, 1470, 790);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dob2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dob2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dob2ActionPerformed

    private void fname2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fname2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fname2ActionPerformed

    private void ad2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ad2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ad2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        
        int r = jTable1.getSelectedRow();
        
        String id = jTable1.getValueAt(r, 0).toString();
        
        try{
            String query = "SELECT * FROM student WHERE stu_id = '"+id+"'";
            pst2 = con2.prepareStatement(query);
            ResultSet rst = pst2.executeQuery();
            
            while(rst.next()){
                jLabel9.setText(id);
                ProfilePicture.viewProfilePicture(pst2, con2, jLabel13,id);
                fname2.setText(rst.getString("stu_fname"));
                mname2.setText(rst.getString("stu_mname"));
                lname2.setText(rst.getString("stu_surname"));
                ad2.setText(rst.getString("address"));
                tpnum2.setText(rst.getString("phone"));
                dob2.setText(rst.getString("dob"));
                email2.setText(rst.getString("email"));
                semester.setSelectedItem(Integer.toString(rst.getInt("cur_sem")));
            }
        }
        catch(Exception e){
        
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String sid = jLabel9.getText();
        String first_name = fname2.getText();
        String middle_name = mname2.getText();
        String last_name = lname2.getText();
        String address = ad2.getText();
        String phone = tpnum2.getText();
        String date_of_birth = dob2.getText();
        String mail = email2.getText();
        int sem = Integer.parseInt(semester.getSelectedItem().toString());
        if(sid=="" || first_name=="" || middle_name=="" || last_name=="" || address=="" || phone=="" || date_of_birth=="" || mail=="" ){
            JOptionPane.showMessageDialog(null, "Please select a record to be updated!");
        }
        else{
            int choice = JOptionPane.showConfirmDialog(null,"Äre you sure you want to update this record?");
            if(choice==0){

                s.updateRecord(sid, first_name, middle_name, last_name, address, phone, date_of_birth, mail,sem);
                s.viewStudent(jTable1);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        int choice = JOptionPane.showConfirmDialog(null,"Äre you sure you want to delete this record?");
        if(choice==0){
            String sid = jLabel9.getText();
            s.deleteRecord(sid);
            s.viewStudent( jTable1);
            JOptionPane.showMessageDialog(null,"Record Deleted!");
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ad2;
    private javax.swing.JTextField dob2;
    private javax.swing.JTextField email2;
    private javax.swing.JTextField fname2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField lname2;
    private javax.swing.JTextField mname2;
    private javax.swing.JComboBox semester;
    private javax.swing.JTextField tpnum2;
    // End of variables declaration//GEN-END:variables
}
