/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interf;

import Codes.DBconnect;
import Codes.grades;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Dinuksha
 */
public class ViewCourseGrades extends javax.swing.JInternalFrame {
    Connection con = null;
    PreparedStatement pst = null;
    grades g3;
    /**
     * Creates new form ViewCourseGrades
     */
    public ViewCourseGrades() {
        
        initComponents();
        con = DBconnect.connect();
        g3 = new grades(con,pst);
        getCourses();
        getExamCode();
        jTable1.setVisible(false);
        
    }
    
    
    public void getCourses(){
    try{
            String sql = "Select * from course";
            pst= con.prepareStatement(sql);
            ResultSet r1 = pst.executeQuery();

            while(r1.next()){
            
                jComboBox1.addItem(r1.getString("name"));
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    public void getExamCode(){
    try{
            String sql = "Select * from exam";
            pst= con.prepareStatement(sql);
            ResultSet r1 = pst.executeQuery();

            while(r1.next()){
            
                jComboBox2.addItem(r1.getString("exam_code"));
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1300, 640));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel1.setText("Course ID: ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(180, 40, 100, 23);

        jComboBox1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Course" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(300, 40, 359, 30);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/showGrades.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/showGradesPressed.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1060, 30, 160, 40);

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setText("Exam Code:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(680, 40, 100, 23);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 100, 1227, 402);

        jComboBox2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Exam Code" }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(785, 39, 180, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Light-Blue-blur-background1.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-6, -6, 1350, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String course = jComboBox1.getSelectedItem().toString();
        String exam = jComboBox2.getSelectedItem().toString();
        
        if(exam.equals("Select Exam Code")){
            try{
                g3.getCourseGrades(jTable1, course);
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        else{
            g3.getCourseGrades(jTable1, course, Integer.parseInt(exam));
        }
        jTable1.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
