/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interf;

import Codes.DBconnect;
import interf.CourseStudents;
import interf.assignLecturerCourse;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.HashMap;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Himasha Harinda
 */
public class ViewCourses extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement pst = null; 
    ResultSet rs = null;
    ResultSet rs1 = null;
    ResultSet rs2 = null;
    ResultSet rs3 = null;
    Connection con1 = null;
    PreparedStatement pst1 = null;
    PreparedStatement pst2 = null;
    PreparedStatement pst3 = null;
    
    /**
     * Creates new form ViewCourses
     */
    public ViewCourses() {
        initComponents();
        con = DBconnect.connect();
        fillcombo();
        tableload();
    }
    
    private void fillcombo()
    {
        try {
            
            String sql = "SELECT * FROM program";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            
            while(rs.next())
            {
                String name = rs.getString("name");
                programbox.addItem(name);
            }
            
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    
    
    
    
    
    
    public void tableload()
    {
        try {
            String sql = "SELECT c.Course_id AS CourseID, c.name AS Name , c.description AS Description,pr.name AS Program,p.academic_year AS Academic_year ,p.semester AS Semester FROM course c,programs_and_courses p,program pr WHERE c.Course_id = p.course_code AND p.program_code = pr.program_id";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            
            tablecourse.setModel(DbUtils.resultSetToTableModel(rs));
            
            
        } catch (Exception e) {
        }
        
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        programbox = new javax.swing.JComboBox();
        academicbox = new javax.swing.JComboBox();
        semesterbox = new javax.swing.JComboBox();
        namebox = new javax.swing.JTextField();
        descbox = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablecourse = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        idbox = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(290, 75));
        setPreferredSize(new java.awt.Dimension(800, 650));
        setSize(new java.awt.Dimension(800, 650));
        getContentPane().setLayout(null);

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rsz_arrow-back-icon.png"))); // NOI18N
        jButton7.setText("Back");
        jButton7.setContentAreaFilled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(680, 0, 120, 70);

        jButton6.setText("Report");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(670, 550, 80, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Name                    :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(190, 250, 130, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Description             :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(190, 290, 160, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Program                 :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(190, 330, 130, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Academic year        :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(190, 380, 120, 40);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Semester               :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(190, 440, 120, 20);

        programbox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Program" }));
        getContentPane().add(programbox);
        programbox.setBounds(360, 340, 230, 20);

        academicbox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Academic Year", "1", "2", "3", "4" }));
        getContentPane().add(academicbox);
        academicbox.setBounds(360, 390, 230, 20);

        semesterbox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Semester", "1", "2", "3", "4", "5", "6", "7", "8" }));
        getContentPane().add(semesterbox);
        semesterbox.setBounds(360, 440, 230, 20);
        getContentPane().add(namebox);
        namebox.setBounds(360, 250, 231, 30);
        getContentPane().add(descbox);
        descbox.setBounds(360, 290, 231, 30);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/insert.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PressedInsert.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(160, 490, 120, 33);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button(13).png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pressedupdate.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(330, 490, 114, 33);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button(17).png"))); // NOI18N
        jButton3.setContentAreaFilled(false);
        jButton3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/presseddelete.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(490, 490, 120, 33);

        tablecourse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablecourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablecourseMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablecourse);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(80, 30, 611, 132);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Course ID              :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(190, 210, 120, 30);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(631, 199, 0, 0);
        getContentPane().add(idbox);
        idbox.setBounds(360, 210, 231, 30);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/assn lectrrs.png"))); // NOI18N
        jButton4.setContentAreaFilled(false);
        jButton4.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/assn lectrrsPressed.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(420, 550, 190, 34);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/stdEnrllmnts.png"))); // NOI18N
        jButton5.setContentAreaFilled(false);
        jButton5.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/stdEnrllmntsPressed.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(160, 550, 200, 34);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Merideth-blog-post11.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, -60, 1100, 280);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Light-Blue-blur-background1.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(-70, -20, 880, 630);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String name = namebox.getText();
        String desc = descbox.getText();
        String prog = programbox.getSelectedItem().toString();
        String acad = academicbox.getSelectedItem().toString();
        String seme = semesterbox.getSelectedItem().toString();
        
        int academic = Integer.parseInt(acad);
        int semester = Integer.parseInt(seme);
        
        boolean no = false;
        
        
        
        if(name.equals("")||desc.equals("")|| programbox.getSelectedItem().toString().length() == 14)
        {
            JOptionPane.showMessageDialog(null," One or more fields are missing !!");
        }
        else
        {
            no = true;
        }
        
        
       
        
        
        try {
            
            String q = "SELECT * FROM course WHERE name = '"+ name +"' AND description = '"+ desc +"'";
            pst = con.prepareStatement(q);
            rs = pst.executeQuery();
            
            boolean exist = false;
            
            while(rs.next())
            {
                String n = rs.getString("name");
            
                if(n.equals(name))
                {
                    JOptionPane.showMessageDialog(null," Data already exists ! ");
                    exist = true ;
                }
                
            }
            
            if(exist == false && no ==  true)
            {
                String qy1 = "SELECT * FROM program WHERE name = '"+ prog +"'";
                pst1 = con.prepareStatement(qy1);
                rs1 = pst1.executeQuery();
                
                while(rs1.next())
                {
                    
                    int programid = rs1.getInt("program_id");
                    
                    String qy = "INSERT INTO course (name,description) VALUES ('"+ name +"' , '"+ desc +"')";
                    pst2 = con.prepareStatement(qy);
                    pst2.execute();
                    
                    String y = "SELECt * FROM course WHERE name ='"+ name +"'";
                    pst3 = con.prepareStatement(y);
                    rs3 = pst3.executeQuery();
                    
                    
                    while(rs3.next())
                    {
                        int coid12 = rs3.getInt("Course_id");
                
                        String sql2 = "INSERT INTO programs_and_courses VALUES ("+ programid +", "+ coid12 +"," + semester + "," + academic +")";
                        pst = con.prepareStatement(sql2);
                        pst.execute();
                        
                        
                        JOptionPane.showMessageDialog(null, " Data has been added !! ");
                        
                    }
                }
            }
            
            tableload();
        } catch (Exception e) {
        }
        
        try {
            
        } catch (Exception e) {
        }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tablecourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablecourseMouseClicked
        
        int r = tablecourse.getSelectedRow();
        
        String id  = tablecourse.getValueAt(r, 0).toString();
        String name = tablecourse.getValueAt(r, 1).toString();
        String desc = tablecourse.getValueAt(r, 2).toString();
        String program = tablecourse.getValueAt(r, 3).toString();
        String academic = tablecourse.getValueAt(r, 4).toString();
        String semester = tablecourse.getValueAt(r, 5).toString();
        
        namebox.setText(name);
        descbox.setText(desc);
        idbox.setText(id);
        programbox.setSelectedItem(program);
        academicbox.setSelectedItem(academic);
        semesterbox.setSelectedItem(semester);
            
    }//GEN-LAST:event_tablecourseMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int x = JOptionPane.showConfirmDialog(null, "Are you sure you want to update?");
        if (x==0)
        {
            String id = idbox.getText();
            String name = namebox.getText();
            String desc = descbox.getText();
            String programName = programbox.getSelectedItem().toString();
            String academicYear = academicbox.getSelectedItem().toString();
            String semester = semesterbox.getSelectedItem().toString();
            
            int year = Integer.parseInt(academicYear);
            int sem = Integer.parseInt(semester);
            
            boolean no = false;
            
            if(name.equals("")||desc.equals("")|| programbox.getSelectedItem().toString().length() == 14)
            {
                JOptionPane.showMessageDialog(null," One or more fields are missing !!");
            }
            else
            {
                no = true;
            }
            
            try {
                String sql2 = "SELECT * FROM program WHERE name = '"+ programName +"'";
                pst2 = con.prepareStatement(sql2);
                rs2 = pst2.executeQuery();
                
                while(rs2.next())
                {
                    int progID = rs2.getInt("program_id");
                    
                    if(no == true)
                    {
                        String sql = "UPDATE course SET name = '"+ name  +"', description = '"+ desc +"'   WHERE Course_id = '"+ id +"'";
                        pst = con.prepareStatement(sql);
                        pst.execute();
                    
                        String q = "UPDATE programs_and_courses SET program_code = '"+ progID +"', semester = '"+ sem +"',academic_year = '"+ year +"' WHERE Course_code = '"+ id +"' ";
                        pst2 = con.prepareStatement(q);
                        pst2.execute();
                    
                    
                        JOptionPane.showMessageDialog(null,"Data has been updated !!");
                    }
                }
                
                tableload();
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        int x = JOptionPane.showConfirmDialog(null,"Are you sure you want to delete?");
        
        if(x==0)
        {
            String id = idbox.getText();
            
            String sql = "DELETE FROM course WHERE Course_id = '"+ id +"'";
            String sql1 = "DELETE FROm programs_and_courses WHERE course_code = '"+ id +"'";
            try {
                pst = con.prepareStatement(sql);
                pst.execute();
                
                pst2 = con.prepareStatement(sql1);
                pst2.execute();
                
                JOptionPane.showMessageDialog(null, "Data has been deleted !!");
                
                tableload();
            } catch (Exception e) {
            }
            
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        assignLecturerCourse c = new assignLecturerCourse();
        c.setVisible(true);     
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
        CourseStudents c = new CourseStudents();
        c.setVisible(true);       
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try{
            String rep="C:\\Users\\Joel\\Desktop\\updated\\SIS\\src\\Reports\\ireport.jrxml";
          
           
            JasperReport jr = JasperCompileManager.compileReport(rep);
            JasperPrint jp = JasperFillManager.fillReport(jr, null,con);
            JasperViewer.viewReport(jp,false);
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCourses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCourses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCourses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCourses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCourses().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox academicbox;
    private javax.swing.JTextField descbox;
    private javax.swing.JLabel idbox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField namebox;
    private javax.swing.JComboBox programbox;
    private javax.swing.JComboBox semesterbox;
    private javax.swing.JTable tablecourse;
    // End of variables declaration//GEN-END:variables
}
